# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KHS(object):
    def setupUi(self, KHS):
        KHS.setObjectName("KHS")
        KHS.resize(400, 208)
        self.target_time = QtWidgets.QTimeEdit(KHS)
        self.target_time.setGeometry(QtCore.QRect(10, 130, 171, 31))
        self.target_time.setAlignment(QtCore.Qt.AlignCenter)
        self.target_time.setTime(QtCore.QTime(0, 0, 0))
        self.target_time.setObjectName("target_time")
        self.target_domain = QtWidgets.QLineEdit(KHS)
        self.target_domain.setGeometry(QtCore.QRect(10, 40, 251, 20))
        self.target_domain.setObjectName("target_domain")
        self.label = QtWidgets.QLabel(KHS)
        self.label.setGeometry(QtCore.QRect(10, 20, 91, 16))
        self.label.setObjectName("label")
        self.start = QtWidgets.QPushButton(KHS)
        self.start.setGeometry(QtCore.QRect(10, 170, 81, 31))
        self.start.setObjectName("start")
        self.label_2 = QtWidgets.QLabel(KHS)
        self.label_2.setGeometry(QtCore.QRect(10, 110, 31, 21))
        self.label_2.setObjectName("label_2")
        self.cancle = QtWidgets.QPushButton(KHS)
        self.cancle.setGeometry(QtCore.QRect(100, 170, 81, 31))
        self.cancle.setObjectName("cancle")
        self.label_3 = QtWidgets.QLabel(KHS)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 121, 16))
        self.label_3.setObjectName("label_3")
        self.open_url = QtWidgets.QLineEdit(KHS)
        self.open_url.setGeometry(QtCore.QRect(10, 90, 251, 21))
        self.open_url.setText("")
        self.open_url.setObjectName("open_url")
        self.detail = QtWidgets.QPushButton(KHS)
        self.detail.setGeometry(QtCore.QRect(190, 170, 71, 31))
        self.detail.setObjectName("detail")
        self.stat = QtWidgets.QTextBrowser(KHS)
        self.stat.setGeometry(QtCore.QRect(270, 10, 120, 191))
        self.stat.setObjectName("stat")

        self.retranslateUi(KHS)
        QtCore.QMetaObject.connectSlotsByName(KHS)

    def retranslateUi(self, KHS):
        _translate = QtCore.QCoreApplication.translate
        KHS.setWindowTitle(_translate("KHS", "KHS"))
        self.target_time.setDisplayFormat(_translate("KHS", "hh:mm"))
        self.label.setText(_translate("KHS", "타겟 도메인"))
        self.start.setText(_translate("KHS", "확인"))
        self.label_2.setText(_translate("KHS", "시간"))
        self.cancle.setText(_translate("KHS", "취소"))
        self.label_3.setText(_translate("KHS", "원하는 주소"))
        self.detail.setText(_translate("KHS", "상세"))
        self.stat.setHtml(_translate("KHS", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">타겟 도메인은 https://를 지우고 넣어주세요</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    KHS = QtWidgets.QDialog()
    ui = Ui_KHS()
    ui.setupUi(KHS)
    KHS.show()
    sys.exit(app.exec_())
